"""created login table

Revision ID: 942a619adf61
Revises: 8a90e9bc2517
Create Date: 2023-08-07 13:01:58.550923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '942a619adf61'
down_revision = '8a90e9bc2517'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login',
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('login')
    # ### end Alembic commands ###
